[workspace]
members = ["transprompt-examples"]

[workspace.package]
edition = "2021"
authors = ["feng liang <feng.liang@kaust.edu.sa>"]
license-file = "LICENSE"
repository = "https://github.com/ifsheldon/transprompt"

[package]
name = "transprompt"
version = "0.4.0-beta"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
readme = "README.md"
description = "Prompt-centric framework for developing LLM applications in Rust"

[dependencies]
serde_json = "~1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
lazy_static = "1.4.0"
async-trait = "0.1.68"
log = "0.4"
anyhow = "~1.0"
url = "~2.4"
readonly = "~0.2"

# Database related
qdrant-client = "~1.4"
# Token related
tiktoken-rs = { version = "~0.5", features = ["async-openai"] }
# LLM
async-openai = "~0.14"